<a href="https://colab.research.google.com/github/anishkr-sahu/revision_ml/blob/main/nlp_day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
# Text Preprocessing
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [57]:
# tokenization
# word tokenization
from nltk.tokenize import word_tokenize
text = "NLP is very interesting domain happiness gathering studying listening hopping. nlp is the best subject in AI"
tokens = word_tokenize(text)
print(tokens)

['NLP', 'is', 'very', 'interesting', 'domain', 'happiness', 'gathering', 'studying', 'listening', 'hopping', '.', 'nlp', 'is', 'the', 'best', 'subject', 'in', 'AI']


In [58]:
# sentence tokenization
from nltk.tokenize import sent_tokenize
text1 = "NLP is very interesting domain. NLP is used in chatbot"
tokens1 = sent_tokenize(text1)
print(tokens1)

['NLP is very interesting domain.', 'NLP is used in chatbot']


In [59]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [60]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
print(stop_words)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she

In [61]:
# remove the stopwords
stop_words1 = set(stopwords.words('english'))
filter = [w for w in tokens if w.lower() not in stop_words1]
print(filter)

['NLP', 'interesting', 'domain', 'happiness', 'gathering', 'studying', 'listening', 'hopping', '.', 'nlp', 'best', 'subject', 'AI']


In [62]:
# stemming
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
stemmed_words = [stemmer.stem(word) for word in filter]
print(stemmed_words)

['nlp', 'interest', 'domain', 'happi', 'gather', 'studi', 'listen', 'hop', '.', 'nlp', 'best', 'subject', 'ai']


In [63]:
# lemmatization
nltk.download('wordnet')
nltk.download('omw-1.4')

from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
lemmatized_words = [lemmatizer.lemmatize(word, pos='v') for word in filter ]
print(lemmatized_words)

['NLP', 'interest', 'domain', 'happiness', 'gather', 'study', 'listen', 'hop', '.', 'nlp', 'best', 'subject', 'AI']


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [64]:
# bag of words
converted_text = " ".join(lemmatized_words)
print(converted_text)

NLP interest domain happiness gather study listen hop . nlp best subject AI


In [84]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [converted_text]
vectorize = CountVectorizer(ngram_range=(1,3))  # ngram
vectorized_text = vectorize.fit_transform(corpus)
print(vectorize.get_feature_names_out())
print(vectorized_text.toarray())

['ai' 'best' 'best subject' 'best subject ai' 'domain' 'domain happiness'
 'domain happiness gather' 'gather' 'gather study' 'gather study listen'
 'happiness' 'happiness gather' 'happiness gather study' 'hop' 'hop nlp'
 'hop nlp best' 'interest' 'interest domain' 'interest domain happiness'
 'listen' 'listen hop' 'listen hop nlp' 'nlp' 'nlp best'
 'nlp best subject' 'nlp interest' 'nlp interest domain' 'study'
 'study listen' 'study listen hop' 'subject' 'subject ai']
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1]]


In [66]:
# tf-idf
from sklearn.feature_extraction.text import TfidfVectorizer
corpus1 = [converted_text]
vectorizer1 = TfidfVectorizer()
vectorized_text1 = vectorizer1.fit_transform(corpus1)
print(vectorizer1.get_feature_names_out())
print(vectorized_text1.toarray())

['ai' 'best' 'domain' 'gather' 'happiness' 'hop' 'interest' 'listen' 'nlp'
 'study' 'subject']
[[0.26726124 0.26726124 0.26726124 0.26726124 0.26726124 0.26726124
  0.26726124 0.26726124 0.53452248 0.26726124 0.26726124]]


In [67]:
# word2vec

sentences = [
    ["nlp", "is", "Interesting"],
    ["machine", "learning","is","powerful"],
    ["deep","learning","is","advanced"],
    ["nlp","and","machine","learning"],
    ["i","love","studying","nlp"],
    ["students","prefer","machine","learning"],
    ["nlp","helps","in","text","processing"],
    ["learning","new","'topics","is","fun"],
    ["artificial","Intelligence","is","future"]
]

In [68]:
!pip install gensim

In [69]:
from gensim.models import Word2Vec
model = Word2Vec(
    sentences,
    vector_size=50,
    window=3,
    min_count=1,
    workers=700
)

In [70]:
print("Vector for nlp")
print(model.wv['nlp'])

Vector for nlp
[-0.0172385   0.00733054  0.01037987  0.01148296  0.0149314  -0.01233623
  0.00221015  0.01209577 -0.00568088 -0.01235019 -0.00081942 -0.01673954
 -0.01119835  0.01421161  0.00670445  0.01445334  0.01360277  0.01506222
 -0.00757942 -0.00112307  0.00469667 -0.00903924  0.01677942 -0.01971529
  0.01352862  0.00583053 -0.00986593  0.00879769 -0.00347934  0.01342519
  0.01993117 -0.00872741 -0.00120124 -0.0113933   0.00770338  0.00557218
  0.0137809   0.01220248  0.01908012  0.01854657  0.01579589 -0.0139788
 -0.01831177 -0.00071232 -0.00620046  0.01578948  0.01188056 -0.00309005
  0.00302338  0.0035778 ]


In [71]:
print("\nwords similar to nlp")
print(model.wv.most_similar('nlp'))


words similar to nlp
[('i', 0.19606032967567444), ('future', 0.1655939370393753), ('text', 0.15516488254070282), ('students', 0.1438673436641693), ('Interesting', 0.14380493760108948), ("'topics", 0.13940690457820892), ('learning', 0.1266929656267166), ('processing', 0.1212104856967926), ('studying', 0.1051679477095604), ('artificial', 0.08864957094192505)]


In [72]:
# vocabulary
print("Vocabulary: ")
print(model.wv.index_to_key)

Vocabulary: 
['learning', 'is', 'nlp', 'machine', 'future', 'Intelligence', 'artificial', 'fun', "'topics", 'new', 'processing', 'text', 'in', 'helps', 'prefer', 'students', 'studying', 'love', 'i', 'and', 'advanced', 'deep', 'powerful', 'Interesting']


In [73]:
# sentence to vector
import numpy as np
def sent_vec(sentence):
  words = sentence.lower().split()
  vectors = []
  for word in words:
    if word in model.wv:
      vectors.append(model.wv[word])
  return np.mean(vectors,axis=0)

sentence = "NLP is interesting"
vec = sent_vec(sentence)
print("sentence vector: ")
print(vec)

sentence vector: 
[-0.01678396  0.00816661  0.00104949  0.0065669   0.01597418 -0.01063185
  0.00562576 -0.00074555 -0.00638919  0.00323263 -0.00198961 -0.00804655
 -0.00974465 -0.0005832   0.00184576  0.00969305  0.00590767  0.01306519
 -0.00653102  0.00169781  0.00780804  0.00383027  0.00693177 -0.01907376
  0.01113785  0.0034838   0.0025144   0.00358176 -0.00437892 -0.00204675
  0.00910789 -0.00153457  0.00480857  0.00136307 -0.00185829  0.00464772
  0.01298595  0.00130275  0.00642487  0.01607393  0.00952986 -0.00679925
 -0.00567901 -0.00013747  0.00652282  0.01295804 -0.00298484 -0.00859122
  0.00241311  0.00818836]


In [74]:
# Cosine similarity score
from sklearn.metrics.pairwise import cosine_similarity

s1 = sent_vec("nlp is interesting")
s2 = sent_vec("ai learnig is interesting")
similarity = cosine_similarity([s1],[s2])
print("sentence similarity\n")
print(similarity[0][0])

sentence similarity

0.6699645


In [79]:
import numpy as np
# Text classification
from sklearn.linear_model import LogisticRegression

x = [
    sent_vec("nlp is interesting"),
    sent_vec("machine learning is interesting"),
    sent_vec("I hate studying nlp"),
    sent_vec("deep learning is boring")
]
y = [1,1,0,0]

model_1 = LogisticRegression()
model_1.fit(x,y)

test = sent_vec("i don't like nlp")
print("Predictions: ", model_1.predict([test]))

Predictions:  [0]


In [80]:
from sklearn.cluster import KMeans
x = [
    sent_vec("nlp is interesting"),
    sent_vec("machine learning is interesting"),
    sent_vec("I hate studying nlp"),
    sent_vec("deep learning is boring")
]

kmeans = KMeans(n_clusters=2)
kmeans.fit(x)
print("Cluster: ", kmeans.labels_)

Cluster:  [1 0 1 0]


## N-grams

N-grams are contiguous sequences of N items from a given sample of text or speech. The items can be characters, syllables, or words. N-grams are widely used in natural language processing (NLP) for various tasks such as language modeling, text classification, spell checking, and machine translation.

Here are some common types of n-grams:

*   **Unigrams (1-gram):** Individual words (e.g., "the", "cat", "sat").
*   **Bigrams (2-gram):** Pairs of adjacent words (e.g., "the cat", "cat sat", "sat on").
*   **Trigrams (3-gram):** Triplets of adjacent words (e.g., "the cat sat", "cat sat on").

### How N-grams are used:

1.  **Language Modeling:** Predicting the next word in a sequence based on the preceding `N-1` words.
2.  **Text Classification:** Features for classifying text documents.
3.  **Spell Correction:** Identifying probable misspellings by checking if sequences of characters or words are common.
4.  **Information Retrieval:** Matching queries to documents.
5.  **Machine Translation:** Evaluating the fluency of translated text.

In [81]:
from nltk.util import ngrams
from nltk.tokenize import word_tokenize

# Example text
text_for_ngram = "NLP is a fascinating field. It helps in understanding and processing human language."

# Tokenize the text into words
words_for_ngram = word_tokenize(text_for_ngram.lower())

print(f"Original text: {text_for_ngram}")
print(f"Tokenized words: {words_for_ngram}\n")

# Generate unigrams (1-grams)
unigrams = list(ngrams(words_for_ngram, 1))
print(f"Unigrams (1-grams): {unigrams}\n")

# Generate bigrams (2-grams)
bigrams = list(ngrams(words_for_ngram, 2))
print(f"Bigrams (2-grams): {bigrams}\n")

# Generate trigrams (3-grams)
trigrams = list(ngrams(words_for_ngram, 3))
print(f"Trigrams (3-grams): {trigrams}")

Original text: NLP is a fascinating field. It helps in understanding and processing human language.
Tokenized words: ['nlp', 'is', 'a', 'fascinating', 'field', '.', 'it', 'helps', 'in', 'understanding', 'and', 'processing', 'human', 'language', '.']

Unigrams (1-grams): [('nlp',), ('is',), ('a',), ('fascinating',), ('field',), ('.',), ('it',), ('helps',), ('in',), ('understanding',), ('and',), ('processing',), ('human',), ('language',), ('.',)]

Bigrams (2-grams): [('nlp', 'is'), ('is', 'a'), ('a', 'fascinating'), ('fascinating', 'field'), ('field', '.'), ('.', 'it'), ('it', 'helps'), ('helps', 'in'), ('in', 'understanding'), ('understanding', 'and'), ('and', 'processing'), ('processing', 'human'), ('human', 'language'), ('language', '.')]

Trigrams (3-grams): [('nlp', 'is', 'a'), ('is', 'a', 'fascinating'), ('a', 'fascinating', 'field'), ('fascinating', 'field', '.'), ('field', '.', 'it'), ('.', 'it', 'helps'), ('it', 'helps', 'in'), ('helps', 'in', 'understanding'), ('in', 'understan

## N-grams for Text Classification

N-grams can be used as features to train a text classification model. Here, we'll demonstrate a simple example using `CountVectorizer` to extract bigram features from a small corpus and then train a `LogisticRegression` model.

In [82]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from nltk.tokenize import word_tokenize

# 1. Sample Dataset
# Let's classify sentences as positive (1) or negative (0) sentiment
corpus_classification = [
    "This movie is great and fantastic",
    "I love this amazing film",
    "What a terrible movie, it's boring",
    "I hate this film, it's awful"
]
labels_classification = [1, 1, 0, 0]

# 2. Preprocessing (Tokenization and N-gram generation)
# We'll use bigrams (n-gram of 2 words) for this example

# You might need to preprocess further (like removing stopwords, stemming/lemmatization)
# For simplicity, we'll just tokenize and generate n-grams.

# Tokenize and rejoin for CountVectorizer
processed_corpus = []
for doc in corpus_classification:
    tokens_clf = word_tokenize(doc.lower())
    processed_corpus.append(" ".join(tokens_clf))

# Create CountVectorizer with bigram range
vectorizer_ngram = CountVectorizer(ngram_range=(1, 2)) # Using unigrams and bigrams
X_ngram = vectorizer_ngram.fit_transform(processed_corpus)

print("Features (N-grams):\n", vectorizer_ngram.get_feature_names_out())
print("\nVectorized N-gram features for corpus:\n", X_ngram.toarray())


Features (N-grams):
 ['amazing' 'amazing film' 'and' 'and fantastic' 'awful' 'boring'
 'fantastic' 'film' 'film it' 'great' 'great and' 'hate' 'hate this' 'is'
 'is great' 'it' 'it awful' 'it boring' 'love' 'love this' 'movie'
 'movie is' 'movie it' 'terrible' 'terrible movie' 'this' 'this amazing'
 'this film' 'this movie' 'what' 'what terrible']

Vectorized N-gram features for corpus:
 [[0 0 1 1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 0 0 1 1 0 0 0 1 0 0 1 0 0]
 [1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 1 0 0 0 0 1 1]
 [0 0 0 0 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0]]


In [83]:
# 3. Train a Logistic Regression Classifier
model_ngram = LogisticRegression()
model_ngram.fit(X_ngram, labels_classification)

# 4. Predict on a new sentence
new_sentence = "This film is amazing"

# Preprocess the new sentence the same way
processed_new_sentence = " ".join(word_tokenize(new_sentence.lower()))

# Transform the new sentence using the *same* vectorizer
X_new_ngram = vectorizer_ngram.transform([processed_new_sentence])

prediction_ngram = model_ngram.predict(X_new_ngram)

print(f"\nNew sentence: '{new_sentence}'")
print(f"Predicted sentiment (1=Positive, 0=Negative): {prediction_ngram[0]}")


New sentence: 'This film is amazing'
Predicted sentiment (1=Positive, 0=Negative): 1


In [87]:
# advanced natural language processing
processed_docs = [
    ['foods','delicious','restuarant','great','service'],
    ['love','eating','pizza','pasta'],
    ['stock','market','creashed','economic','slowdown'],
    ['investors','worried','market','volatility'],
    ['chef','prepared','wonderful','meal'],
    ['stocks','bonds','important','investment']
]

from gensim import corpora
from gensim.models import LdaModel

dictionary = corpora.Dictionary(processed_docs) # each word get an unique numerical id
corpus = [dictionary.doc2bow(doc) for doc in processed_docs]  # it gives word_id , frequency
lda_model = LdaModel(
    corpus= corpus,
    id2word= dictionary, # mapping word id
    num_topics= 2,       # no of words
    random_state= 42,
    passes= 10           # no of iterations
)

topics = lda_model.print_topics(num_words=6)
for topic in topics:
  print(topic)

for i,doc in enumerate(corpus):
  print(f"Document {i}: ", lda_model[doc])

(0, '0.069*"service" + 0.069*"delicious" + 0.069*"restuarant" + 0.069*"great" + 0.069*"foods" + 0.069*"pasta"')
(1, '0.085*"market" + 0.051*"creashed" + 0.051*"economic" + 0.051*"stock" + 0.051*"worried" + 0.051*"prepared"')
Document 0:  [(0, np.float32(0.9141058)), (1, np.float32(0.08589425))]
Document 1:  [(0, np.float32(0.89691156)), (1, np.float32(0.10308842))]
Document 2:  [(0, np.float32(0.08805287)), (1, np.float32(0.9119471))]
Document 3:  [(0, np.float32(0.10551284)), (1, np.float32(0.8944872))]
Document 4:  [(0, np.float32(0.10640625)), (1, np.float32(0.8935937))]
Document 5:  [(0, np.float32(0.106418684)), (1, np.float32(0.89358133))]


In [88]:
!pip install pyLDAvis

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 30.6 MB/s eta 0:00:00


In [89]:
import pyLDAvis
import pyLDAvis.gensim_models

# Prepare the visualization
lda_display = pyLDAvis.gensim_models.prepare(lda_model, corpus, dictionary, sort_topics=False)

# Display the visualization
pyLDAvis.display(lda_display)

/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.13/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
